server:
  port: 8080
spring:
  application:
    name: grpc-api-gateway
  main:
    web-application-type: reactive
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: grpc-order
          uri: lb://grpc-order
          predicates:
            - Path=/**
        - id: grpc-payment
          uri: lb://payment
          predicates:
            - Path=/payment/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
